name: Salesforce Deployment Workflow

on:
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests to the main branch

jobs:
  deploy:
    name: Deploy Salesforce Changes
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Salesforce CLI
      - name: Install Salesforce CLI
        uses: dxatscale/sfdx-action@v1
        with:
          version: latest

      # Step 3: Authenticate to Dev1
      - name: Authenticate to Dev1
        run: |
          echo "${{ secrets.JWT_KEY }}" > server.key
          sfdx force:auth:jwt:grant \
            --clientid ${{ secrets.DEV1_CLIENT_ID }} \
            --jwtkeyfile server.key \
            --username ${{ secrets.DEV1_USERNAME }} \
            --instanceurl https://test.salesforce.com

      # Step 4: Retrieve changes from Dev1
      - name: Retrieve Metadata from Dev1
        run: |
          sfdx force:source:retrieve -m ApexClass,ApexTrigger,CustomObject

      # Step 5: Authenticate to Test1
      - name: Authenticate to Test1
        run: |
          echo "${{ secrets.JWT_KEY }}" > server.key
          sfdx force:auth:jwt:grant \
            --clientid ${{ secrets.TEST1_CLIENT_ID }} \
            --jwtkeyfile server.key \
            --username ${{ secrets.TEST1_USERNAME }} \
            --instanceurl https://test.salesforce.com

      # Step 6: Deploy changes to Test1
      - name: Deploy Metadata to Test1
        run: |
          sfdx force:source:deploy -m ApexClass,ApexTrigger,CustomObject
